[package]
name = "gtk-tokio-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.18.1"
glib = "0.18.4"
tokio = { version = "1.35.0", features = [ "full" ] }
